name: Test
on:
  push:
    branches-ignore:
      - main
jobs:
  run_tests:
    runs-on: ubuntu-20.04
    container: node:20.15-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        run: npm install
      - name: Run tests
        id: run_node_tests
        run: |
            npm run test --verbose
